version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run: pip install pipenv; pipenv sync -d; pipenv run pytest
workflows:
  version: 2
  test:
    jobs:
      - test
