version: 2
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  test:
    docker:
      - image: circleci/python:3.7.3
    steps:

      - checkout

      - restore_cache:
          key: dependencies-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: Install Dependencies
          command: |
            pip install pipenv
            pipenv sync -d

      - run:
          name: Black Check
          command: |
            pipenv run black --check . --skip-string-normalization \

      - run:
          name: Run Pytest
          command: |
            pipenv run pytest -vvx --ff --cov=src tests/

      - run:
          name : Upload CodeCov
          command: |
            pipenv run codecov -t $CODECOV_TOKEN

      - save_cache:
          key: dependencies-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - "~/.local/share/virtualenvs/"

workflows:
  version: 2
  test:
    jobs:
      - test
